config/routes.rb
Hrcalendar::Application.routes.draw do
  
  resources :users do
    resources :employees 
  end

  resource :sessions, only: [:new, :create, :destroy]
  root 'staticpages#home'

end

app/models/employee.rb
class Employee
  include Mongoid::Document
  field :name, type: String
  field :ssn, type: Integer
  field :hiring_date, type: Date
  field :prob_expire, type: Date
  field :act_insure, type: Date
  field :ann_review, type: Date
  field :birthday, type: Date
  belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document

	attr_accessor :password

  field :username, type: String
  field :email, type: String
  field :salt, type: String
  field :hashed_password, type: String

  validates_uniqueness_of :email
  
  has_many :employees, dependent: :destroy


  def authenticate(password)
  	self.hashed_password == BCrypt::Engine.hash_secret(password, self.salt)
  end
	#this line has to be here. 
	before_save :hashed_word
  private
  def hashed_word
  	self.salt = BCrypt::Engine.generate_salt
  	self.hashed_password = BCrypt::Engine.hash_secret(self.password, self.salt)
  	self.password = nil 
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
  	if !self.current_user
  		redirect_to new_sessions_path
  	end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_action :authenticate_user
	before_action :correct_user
	before_action :set_user
	before_action :set_employee, only: [:show, :edit, :update, :destroy]
	respond_to :json, :html
	
	def index
		@employees = @user.employees
		respond_with @employees
	end

	def show
		respond_with @employee
	end

	def new
		@employee = @user.employees.new
	end

	def create
		
		@employee = @user.employees.new(employee_params)
			respond_to do |format|
				if @employee.save
					format.html { redirect_to @user }
        			format.json { render json: @employee, status: :created }

				else
					format.html { render action: 'new' }
					format.json { render json: @employee.errors, status: :unprocessable_entity }
				end
			end
	end

	def edit
	end

	def update
		if @employee.update_attributes(employee_params)
			respond_to do |format|
			format.html { redirect_to @user }
			format.json { render nothing: true, status: :no_content }
			end
		else
			respond_to do |format|
			format.html { render 'edit' }
			format.json { render json: @employee.errors, status: :unprocessable_entity}
			end
		end
	end
	
	def destroy
		@employee.destroy
		respond_to do |format|
			format.html { redirect_to @user }
			format.json { render json: { head: :ok } }
		end
	end

	private
	def set_user
		@user = User.find(params[:user_id])
	end
	def set_employee
		@employee = current_user.employees.find(params[:id])
	end
	def employee_params
		params.require(:employee).permit(:name, :ssn, :hiring_date, :prob_expire, :act_insure, :ann_review, :birthday)
	end
	def correct_user
		redirect_to new_sessions_path unless current_user == User.find(params[:user_id])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	def create
		@user = User.where(:email => params[:session][:email]).first
		if @user && @user.authenticate(params[:session][:password])
			session[:remember_token] = @user.id.to_s
			@current_user = @user
			redirect_to user_employees_path(@user)
		else
			render 'new'
		end
	end
	def destroy
		session.delete(:remember_token)
		redirect_to :root
	end

end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
	before_action :return_user
	def home
	end

	private
	def return_user
		if current_user
			redirect_to user_employees_path(current_user)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user, except: [:new, :create]
	before_action :set_user, only: [:edit, :update, :show, :preview]
	before_action :correct_user, only: [:edit, :update, :show]
	def index
		@users = User.all
	end

	def preview
		@employees = @user.employees
	end


	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:remember_token] = @user.id.to_s
			@current_user = @user
			redirect_to user_employees_path(@user)
		else
			render 'new'
		end
	end
	
	def show
		@employees = @user.employees
		@employee = @user.employees.new

	end

	def edit
	end

	def update
		if @user.update_attributes(user_params)
			redirect_to @user
		else
			render 'edit'
		end
	end



	private
	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
	def correct_user
		redirect_to new_sessions_path unless current_user == User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
		if session[:remember_token]
			@current_user = User.find(session[:remember_token])
		else
			false
		end
	end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employees/employee_form.html.erb
<form name="employeeForm" class="panel-body" ng-show="formDisplay" novalidate>
				    <div class="form-group">
				        <label>Name:</label>
				        <input name="name" class="form-control" ng-model="currentEmployee.name" required />
				        <div class="error" ng-show="employeeForm.name.$dirty && employeeForm.name.$invalid">
				        	<span class="error" ng-show="employeeForm.name.$error.required">Name can not be blank.</span>
				        </div>
				    </div>
				    <div class="form-group">
				        <label>Social Secure #:</label>
				        <input class="form-control" ng-model="currentEmployee.ssn" />
				    </div>
				    <div class="form-group">
				        <label>Birthday:</label>
				        <input type="date" class="form-control" ng-model="currentEmployee.birthday" />
				    </div>

				    <div class="form-group">
				        <label>Date of hire:</label>
				        <input name="hiredDay" type="date" class="form-control" ng-model="currentEmployee.hiring_date" required />
				        <div class="error" ng-show="employeeForm.hiredDay.$dirty && employeeForm.hiredDay.$invalid">
				        	<span class="error" ng-show="employeeForm.hiredDay.$error.required">Date of hire can not be blank.</span>
				        </div>
				    </div>

				    <div class="form-group">
				        <label>Probation due:</label>
				        <input name="probationEnd" type="date" class="form-control" ng-model="currentEmployee.prob_expire"  />
				   
				    </div>

				    <div class="form-group">
				        <label>Benefit eligible:</label>
				        <input name="benefitStart" type="date" class="form-control" ng-model="currentEmployee.act_insure" />
				        
				    </div>

				    <button class="btn btn-primary" ng-click="saveChange(currentEmployee)" ng-disabled="employeeForm.$invalid">Save</button>
				    <button class="btn btn-primary" ng-click="cancelChange()">Cancel</button>
				</form>

app/views/employees/index.html.erb
	<div id="defaultContainer" data-user-id=<%= @user.id.to_s %> class="row" >
		    <ul class="nav nav-tabs" role="tablist">
				<li><a href="#" ng-click="showDefault()">all employees</a></li>
          		<li><a href="#" ng-click="showMonthly()">Monthly view</a></li>
          		<li><%= link_to 'Edit Account', edit_user_path(current_user) %></li>
			</ul>
		
	<div class = "row">
        <div class="panel-body col-sm-7 col-sm-push-4" style="position:static">

        	<!-- <article -->
        	<div ng-show="defaultView">
			    <div class="input-group">
				    <input type="text" class="form-control" ng-model="quickSearch">
				    <span class="input-group-btn">
					    <button class="btn btn-default" type="button">quick search</button>
				    </span>		     
			   </div>
				<!-- </div> -->
	            <table class="table table-striped table-bordered">
	                <thead>
	                	<tr>
		                	<th>Name</th>
		                	<th>Social #</th>
		                	<th>Options</th>
	                	</tr>
	                </thead>
	                <tbody>
	                    <tr ng-hide="employees.length">
	                        <td colspan="3" class="text-center">There is no employee in your record</td>
	                    </tr>
	                    <tr ng-repeat="e in (employees | orderBy: 'name' | filter:quickSearch)">
	                        <td>{{e.name}}</td>
	                        <td>{{e.ssn}}</td>
	                        <td class="text-center">
	                        	<button class="btn btn-sm btn-primary" ng-click="editOrCreateEmployee(e)">
	                        		Edit
	                        	</button>
	                         	<button class="btn btn-sm btn-primary btn-danger" ng-click="deleteEmployee(e)" >Delete
	                        	</button>
	                        </td>
	                    </tr>
	                </tbody>
	        	</table>
	        </div>




	        <div ng-hide="defaultView">
	        	<div class="well">
	        		<button class="btn btn-primary btn-sm" type="button" ng-click="monthDecrement()" ><span class="glyphicon glyphicon-chevron-left"></button>
	        		<select class="form-control" ng-model="monthSelected" ng-options="month.code as month.label for month in monthOptions"></select>
	        		<button class="btn btn-primary btn-sm" type="button" ng-click="monthIncrement()" ><span class="glyphicon glyphicon-chevron-right"></span></button>
	        	</div>
	        	<table class="table table-striped table-bordered">
	        		<thead>
	        			<tr>
	        				<th>Name</th>
	        				<th><select class="form-control" ng-model="propertySelected" ng-options="property.name as property.label for property in propertyOptions"></select></th>
	        				<th class="text-center">Options</th>

	        			</tr>
	        		</thead>
	        		<tbody>
	        			<tr ng-hide="employees.length">
	        				<td colspan="3" class="text-center">There is no employee in your record</td>
	        			</tr>
	        			<tr ng-repeat="e in employees | dateFilter: propertySelected:monthSelected | orderBy:propertySelected ">
	        				<td>{{e.name}}</td>
		        				<td>{{e[propertySelected] | date: 'dd MMM yyyy'}}</td>
		        				<td class="text-center">
		        					<button class="btn btn-sm btn-primary" ng-click="editOrCreateEmployee(e)">
		        						Edit
		        					</button>
		        					<button class="btn btn-sm btn-primary btn-danger" ng-click="deleteEmployee(e)" >Delete
		        					</button>
		        				</td>
		        			</tr>
		        		</tbody>
		        	</table>
	        	</div>
	 	   </div>



          <!--   </article> -->
            <aside class="panel-body col-sm-5 col-sm-pull-8" style="position:static">
            	<div class=>
	            	<button class="btn btn-primary" 
	                ng-click="listEmployees()">Refresh table</button>
	            	<button class="btn btn-primary" 
	                ng-click="editOrCreateEmployee()">Add  New Employee</button>
	            </div>

                <form name="employeeForm" class="panel-body" ng-show="formDisplay" novalidate>
				    <div class="form-group">
				        <label>Name:</label>
				        <input name="name" class="form-control" ng-model="currentEmployee.name" required />
				        <div class="error" ng-show="employeeForm.name.$dirty && employeeForm.name.$invalid">
				        	<span class="error" ng-show="employeeForm.name.$error.required">Name cannot be blank.</span>
				        </div>
				    </div>
				    <div class="form-group">
				        <label>Social Security #:</label>
				        <input class="form-control" ng-model="currentEmployee.ssn" />
				    </div>
				    <div class="form-group">
				        <label>Birthday:</label>
				        <input type="date" class="form-control" ng-model="currentEmployee.birthday" />
				    </div>

				    <div class="form-group">
				        <label>Date of hire:</label>
				        <input name="hiredDay" type="date" class="form-control" ng-model="currentEmployee.hiring_date" required />
				        <div class="error" ng-show="employeeForm.hiredDay.$dirty && employeeForm.hiredDay.$invalid">
				        	<span class="error" ng-show="employeeForm.hiredDay.$error.required">Date of hire cannot be blank.</span>
				        </div>
				    </div>

				    <div class="form-group">
				        <label>Probation due:</label>
				        <input name="probationEnd" type="date" class="form-control" ng-model="currentEmployee.prob_expire"  />
				   
				    </div>

				    <div class="form-group">
				        <label>Benefit eligible:</label>
				        <input name="benefitStart" type="date" class="form-control" ng-model="currentEmployee.act_insure" />
				        
				    </div>

				    <button class="btn btn-primary" ng-click="saveChange(currentEmployee)" ng-disabled="employeeForm.$invalid">Save</button>
				    <button class="btn btn-primary" ng-click="cancelChange()">Cancel</button>
				</form>
            </aside>
        </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="employeeApp">
<head>
  <title>NewHired</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body ng-controller="defaultCtrl">
<header id="appHeader"></header>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <h4><p>NewHired</p></h4>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to 'Sign Out', sessions_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign Up', new_user_path%></li>
          <li><%= link_to 'Sign In', new_sessions_path %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



			<%= yield %>



</body>
</html>

app/views/staticpages/home.html.erb
<div class="introcontainer">
	<p><h3>Welcome</h3></p>
	<p><h4>
	NewHired helps manage your new workers. Just store your empolyees' info here, and you can always have a quick reference of important dates like when a new worker's probation expires, or someone's annual review is coming up. Save yourself the headache of tracking these things on a post-it.
	</h4></p>
</div>

app/views/users/edit.html.erb
<div class="row">
	<h1>edit your account</h1>
	<%=form_for @user, html: {class: "form-horizontal"} do |f| %>
	<div class="form-group">
		<%= f.label :username, 'User Name', class: "control-label"%>
		<%= f.text_field :username, placeholder: "name", class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :email, 'E-Mail', class: "control-label" %>
		<%= f.text_field :email, placeholder: "email", class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :password, 'Password', class: "control-label" %>
		<%= f.password_field :password, placeholder: "password", class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.submit 'Submit', class: "btn btn-default" %> 
		<%= link_to 'Cancel', user_employees_path(current_user), class: "btn btn-default btn-danger" %>
	</div>	
	<% end %>
	
</div>

app/views/users/index.html.erb
<h1>all users</h1>
<% @users.each do |u| %>
	<%= u.username %> | <%= u.email %> 
	<%= link_to 'details', u %>
<% end %>

app/views/users/new.html.erb
<%=form_for @user, html: {class: "form-horizontal"} do |f| %>
	<div class="form-group">
		<%= f.label :username, 'User Name', class: "control-label"%>
		<%= f.text_field :username, placeholder: "name", class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :email, 'E-Mail', class: "control-label" %>
		<%= f.text_field :email, placeholder: "email", class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :password, 'Password', class: "control-label" %>
		<%= f.password_field :password, placeholder: "password", class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.submit 'Submit', class: "btn btn-default" %> 
		<%= link_to 'Cancel', root_path, class: "btn btn-danger" %> 		
	</div>
	
<% end %>

app/views/users/show.html.erb
<script type="text/javascript">

</script>
<div class="row">	
	<h1>Welcome, <%= @user.username %></h1>
	E-mail: <%= @user.email %><br />
	<%= link_to 'edit your profile', edit_user_path %>
	<hr>

</div>
<div class="row">

	<!-- col-offset to main the distance between 2 columns, push make article stay at the right side in when screen in higher resolution  -->
	<article class="col-sm-7 col-sm-offset-1 col-sm-push-4">
		<div class="table-responsive">
			
				<table class="table" >
					<thead>
						<tr><th>name</th><th>options</th><th></th></tr>
					</thead>

					<tbody id="employees">
					<% if @employees.size > 1 %>
						<%= render @employees  %>
					<% else %>
						<tr id="no_employee_text"><td><p calss="label">no employees available<td><tr><p>
					<% end %>
					</tbody>
				</table>
		<div>
	</article>
	<!-- pull to keep the aside on the left, corresponding to article push, in higher resolution -->
	<aside class="col-sm-4 col-sm-pull-8">
		<%= link_to 'add employees', new_user_employee_path(@user), id: "new_employee_link", remote: true %>
		<br />
		
	</aside>
</div>